services:
  - type: web
    name: garibaldi-tech
    env: python
    buildCommand: "pip install -U pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "waitress-serve --port=$PORT app:app"